import numpy as np
import numpy.typing as npt
from typing import Any, overload
from .._typing import ContextDict, NumericLike, UnitLike, _UnitT

class _DecomposeDispatcher:
    def __call__(self) -> str: ...
    def __get__(self, instance: Any, owner: type) -> '_DecomposeDispatcher': ...

class _PhaethonUnitMeta(type):
    dimension: str | None
    symbol: str | None
    base_multiplier: float
    base_offset: float
    is_anonymous: bool
    __semantic__: str | None
    _signature: frozenset[Any]
    
    def __mul__(cls, other: Any) -> type['BaseUnit']: ...
    def __rmul__(cls, other: Any) -> type['BaseUnit']: ...
    def __truediv__(cls, other: Any) -> type['BaseUnit']: ...
    def __rtruediv__(cls, other: Any) -> type['BaseUnit']: ...
    def __pow__(cls, power: int | float) -> type['BaseUnit']: ...
    def __matmul__(cls, other: type['BaseUnit']) -> type['BaseUnit']: ...
    def __rmatmul__(cls, other: type['BaseUnit']) -> type['BaseUnit']: ...

    def __lt__(cls, other: Any) -> bool: ...
    def __le__(cls, other: Any) -> bool: ...
    def __gt__(cls, other: Any) -> bool: ...
    def __ge__(cls, other: Any) -> bool: ...

class BaseUnit(metaclass=_PhaethonUnitMeta):
    """
    The foundational core class for all units in Phaethon.
    """
    dimension: str | None
    symbol: str | None
    aliases: list[str] | None
    base_multiplier: float
    base_offset: float
    is_anonymous: bool
    __semantic__: str | None
    context: ContextDict

    def __init__(self, value: NumericLike, context: ContextDict | None = ...) -> None: ...

    @property
    def mag(self) -> float | npt.NDArray[np.float64]: ...

    @property
    def si(self) -> 'BaseUnit': ...
    
    @property
    def shape(self) -> tuple[int, ...]: ...

    @property
    def ndim(self) -> int: ...

    @property
    def T(self) -> 'BaseUnit': ...

    def __getitem__(self, key: Any) -> 'BaseUnit': ...

    def __add__(self, other: Any) -> 'BaseUnit': ...
    def __sub__(self, other: Any) -> 'BaseUnit': ...
    def __mul__(self, other: Any) -> 'BaseUnit': ...
    def __truediv__(self, other: Any) -> 'BaseUnit': ...
    def __floordiv__(self, other: Any) -> 'BaseUnit': ...
    def __mod__(self, other: Any) -> 'BaseUnit': ...

    def __radd__(self, other: Any) -> 'BaseUnit': ...
    def __rsub__(self, other: Any) -> 'BaseUnit': ...
    def __rmul__(self, other: Any) -> 'BaseUnit': ...
    def __rtruediv__(self, other: Any) -> 'BaseUnit': ...

    def __pow__(self, power: int | float) -> 'BaseUnit': ...
    def __invert__(self) -> 'BaseUnit': ...
    def __neg__(self) -> 'BaseUnit': ...
    def __pos__(self) -> 'BaseUnit': ...
    def __abs__(self) -> 'BaseUnit': ...
    def __round__(self, ndigits: int | None = ...) -> 'BaseUnit': ...

    def __matmul__(self, other: Any) -> 'BaseUnit': ...
    def __rmatmul__(self, other: Any) -> 'BaseUnit': ...

    def sum(self, axis: int | tuple[int, ...] | None = ..., keepdims: bool = ..., **kwargs: Any) -> 'BaseUnit': ...
    def mean(self, axis: int | tuple[int, ...] | None = ..., keepdims: bool = ..., **kwargs: Any) -> 'BaseUnit': ...
    def max(self, axis: int | tuple[int, ...] | None = ..., keepdims: bool = ..., **kwargs: Any) -> 'BaseUnit': ...
    def min(self, axis: int | tuple[int, ...] | None = ..., keepdims: bool = ..., **kwargs: Any) -> 'BaseUnit': ...

    def reshape(self, shape: tuple[int, ...] | int, *args: Any, order: str = ...) -> 'BaseUnit': ...
    def flatten(self, order: str = ...) -> 'BaseUnit': ...

    @overload
    def to(self, unit: type[_UnitT], context: ContextDict | None = ...) -> _UnitT: ...
    @overload
    def to(self, unit: str, context: ContextDict | None = ...) -> 'BaseUnit': ...
    def to(self, unit: UnitLike, context: ContextDict | None = ...) -> 'BaseUnit' | _UnitT: ...
    
    def format(self, prec: int = ..., sigfigs: int | None = ..., scinote: bool = ..., delim: bool | str = ..., tag: bool = ...) -> str: ...
    
    decompose: _DecomposeDispatcher

    def __eq__(self, other: object) -> bool | npt.NDArray[np.bool_]: ...
    def __ne__(self, other: object) -> bool | npt.NDArray[np.bool_]: ...
    def __lt__(self, other: Any) -> bool | npt.NDArray[np.bool_]: ...
    def __le__(self, other: Any) -> bool | npt.NDArray[np.bool_]: ...
    def __gt__(self, other: Any) -> bool | npt.NDArray[np.bool_]: ...
    def __ge__(self, other: Any) -> bool | npt.NDArray[np.bool_]: ...
    
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def __array__(self, dtype: Any = ...) -> npt.NDArray[Any]: ...
    def __array_ufunc__(self, ufunc: Any, method: str, *inputs: Any, **kwargs: Any) -> Any: ...
    def __array_function__(self, func: Any, types: Any, args: Any, kwargs: Any) -> Any: ...